[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update -y && apt install -y protobuf-compiler libpcap-dev:$CROSS_DEB_ARCH"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update -y && apt install -y protobuf-compiler libpcap-dev:$CROSS_DEB_ARCH"
]

[target.i686-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update -y && apt install -y protobuf-compiler libpcap-dev:$CROSS_DEB_ARCH"
]

[target.i686-unknown-linux-gnu.env]
passthrough = []
# keep pkg-config limited to 32-bit search paths inside the container
PKG_CONFIG_LIBDIR = "/usr/lib/i386-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig"
PKG_CONFIG_PATH = "/usr/lib/i386-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig"

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update -y && apt install -y protobuf-compiler libpcap-dev:$CROSS_DEB_ARCH"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update -y && apt install -y protobuf-compiler libpcap-dev:$CROSS_DEB_ARCH"
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update -y && apt install -y protobuf-compiler libpcap-dev:$CROSS_DEB_ARCH"
]